config/routes.rb
Rails.application.routes.draw do
  resources :options
  resources :newslines
  resources :orders
  get 'bsd-banner', to: 'bannerpartner#index'
  get '/privacy', to: 'infopersonal#index'
  get '/loyalty', to: 'loyalty#index'
  resources :banners
  resources :userroles
  resources :storages
  resources :posts
  # resources :titles
  resources :branches
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :cities

  get 'persons/profile'
  get 'home/index'
  get '/about', to: 'about#index'
  get '/order', to: 'order#index'
  get '/branch_list', to: 'branches#list'

  root to: 'home#index'
end

app/models/banner.rb
class Banner < ApplicationRecord
  mount_uploader :picture, ImageUploader
  belongs_to :branch
end

app/models/branch.rb
class Branch < ApplicationRecord
  has_many :storage, dependent: :destroy
  mount_uploader :background, ImageUploader
  has_many :banners

  has_many :users, through: :branchadmins
  has_many :newslines
end

app/models/branchadmin.rb
class Branchadmin < ApplicationRecord
  belongs_to :branch
  belongs_to :user
end

app/models/cargo.rb
class Cargo < ApplicationRecord
  has_many :orders, dependent: :destroy
end

app/models/city.rb
class City < ApplicationRecord

end

app/models/coin.rb
class Coin < ApplicationRecord
  belongs_to :user
end

app/models/location.rb
class Location < ActiveRecord::Base
  acts_as_mappable :default_units => :miles,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :theme
end

app/models/newsline.rb
class Newsline < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :branch
end

app/models/option.rb
class Option < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  scope :empty_results, -> { where(id: '-1') }
  
  belongs_to :user
  belongs_to :cargo
  belongs_to :payment
  belongs_to :status
end
# o = Order.where(code: 'CC-144-CT-493')

app/models/payment.rb
class Payment < ApplicationRecord
  has_many :order, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :title
  belongs_to :branch
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :userroles
  has_many :users, through: :userroles
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :orders
end

app/models/storage.rb
class Storage < ApplicationRecord
  belongs_to :branch
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_one :theme
end

app/models/title.rb
class Title < ApplicationRecord
  has_one :post
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :coins, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :userroles
  has_many :roles, through: :userroles

  has_many :branchadmins
  has_many :branches, through: :branchadmins

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    !roles.find_by_id(1).nil?
  end
  def director?
    !roles.find_by_id(2).nil?
  end
  def manager?
    !roles.find_by_id(3).nil?
  end
end

app/models/userrole.rb
class Userrole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/newslines_controller.rb
class NewslinesController < ApplicationController
  before_action :set_newsline, only: [:show, :edit, :update, :destroy]

  # GET /newslines
  # GET /newslines.json
  def index
    @newslines = Newsline.all
  end

  # GET /newslines/1
  # GET /newslines/1.json
  def show
  end

  # GET /newslines/new
  def new
    @newsline = Newsline.new
  end

  # GET /newslines/1/edit
  def edit
  end

  # POST /newslines
  # POST /newslines.json
  def create
    @newsline = Newsline.new(newsline_params)

    respond_to do |format|
      if @newsline.save
        format.html { redirect_to @newsline, notice: 'Newsline was successfully created.' }
        format.json { render :show, status: :created, location: @newsline }
      else
        format.html { render :new }
        format.json { render json: @newsline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newslines/1
  # PATCH/PUT /newslines/1.json
  def update
    respond_to do |format|
      if @newsline.update(newsline_params)
        format.html { redirect_to @newsline, notice: 'Newsline was successfully updated.' }
        format.json { render :show, status: :ok, location: @newsline }
      else
        format.html { render :edit }
        format.json { render json: @newsline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newslines/1
  # DELETE /newslines/1.json
  def destroy
    @newsline.destroy
    respond_to do |format|
      format.html { redirect_to newslines_url, notice: 'Newsline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsline
      @newsline = Newsline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsline_params
      params.fetch(:newsline, {})
    end
end

app/helpers/newslines_helper.rb
module NewslinesHelper
end

app/views/newslines/_form.html.erb
<div class="callout">
<%= simple_form_for(@newsline) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :branch %>
    <%= f.file_field :image %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
</div>

app/views/newslines/edit.html.erb
<h1>Editing Newsline</h1>

<%= render 'form', newsline: @newsline %>

<%= link_to 'Show', @newsline %> |
<%= link_to 'Back', newslines_path %>

app/views/newslines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Newslines</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @newslines.each do |newsline| %>
      <tr>
        <td><%= link_to 'Show', newsline %></td>
        <td><%= link_to 'Edit', edit_newsline_path(newsline) %></td>
        <td><%= link_to 'Destroy', newsline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newsline', new_newsline_path %>

app/views/newslines/new.html.erb
<h1>New Newsline</h1>

<%= render 'form', newsline: @newsline %>

<%= link_to 'Back', newslines_path %>

app/views/newslines/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_newsline_path(@newsline) %> |
<%= link_to 'Back', newslines_path %>