config/routes.rb
Rails.application.routes.draw do
  resources :options
  resources :newslines
  resources :orders
  get 'bsd-banner', to: 'bannerpartner#index'
  get '/privacy', to: 'infopersonal#index'
  get '/loyalty', to: 'loyalty#index'
  resources :banners
  resources :userroles
  resources :storages
  resources :posts
  # resources :titles
  resources :branches
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :cities

  get 'persons/profile'
  get 'home/index'
  get '/about', to: 'about#index'
  get '/order', to: 'order#index'
  get '/branch_list', to: 'branches#list'

  root to: 'home#index'
end

app/models/banner.rb
class Banner < ApplicationRecord
  mount_uploader :picture, ImageUploader
  belongs_to :branch
end

app/models/branch.rb
class Branch < ApplicationRecord
  has_many :storage, dependent: :destroy
  mount_uploader :background, ImageUploader
  has_many :banners

  has_many :users, through: :branchadmins
  has_many :newslines
end

app/models/branchadmin.rb
class Branchadmin < ApplicationRecord
  belongs_to :branch
  belongs_to :user
end

app/models/cargo.rb
class Cargo < ApplicationRecord
  has_many :orders, dependent: :destroy
end

app/models/city.rb
class City < ApplicationRecord

end

app/models/coin.rb
class Coin < ApplicationRecord
  belongs_to :user
end

app/models/location.rb
class Location < ActiveRecord::Base
  acts_as_mappable :default_units => :miles,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :theme
end

app/models/newsline.rb
class Newsline < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :branch
end

app/models/option.rb
class Option < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  scope :empty_results, -> { where(id: '-1') }
  
  belongs_to :user
  belongs_to :cargo
  belongs_to :payment
  belongs_to :status
end
# o = Order.where(code: 'CC-144-CT-493')

app/models/payment.rb
class Payment < ApplicationRecord
  has_many :order, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :title
  belongs_to :branch
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :userroles
  has_many :users, through: :userroles
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :orders
end

app/models/storage.rb
class Storage < ApplicationRecord
  belongs_to :branch
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_one :theme
end

app/models/title.rb
class Title < ApplicationRecord
  has_one :post
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :coins, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :userroles
  has_many :roles, through: :userroles

  has_many :branchadmins
  has_many :branches, through: :branchadmins

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    !roles.find_by_id(1).nil?
  end
  def director?
    !roles.find_by_id(2).nil?
  end
  def manager?
    !roles.find_by_id(3).nil?
  end
end

app/models/userrole.rb
class Userrole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :set_banner, only: [:show, :edit, :update, :destroy]

  # GET /banners
  # GET /banners.json
  def index
    @banners = Banner.all
  end

  # GET /banners/1
  # GET /banners/1.json
  # def show
  # end

  # GET /banners/new
  def new
    @banner = Banner.new
    @title = 'Добавить баннер'
  end

  # GET /banners/1/edit
  def edit
    @title ='Изменить баннер'
  end

  # POST /banners
  # POST /banners.json
  def create
    @banner = Banner.new(banner_params)

    respond_to do |format|
      if @banner.save
        format.html { redirect_to persons_profile_url, notice: 'Баннер создан' }
        format.json { render :show, status: :created, location: @banner }
      else
        format.html { render :new }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banners/1
  # PATCH/PUT /banners/1.json
  def update
    respond_to do |format|
      if @banner.update(banner_params)
        format.html { redirect_to persons_profile_url, notice: 'Баннер изменен' }
        format.json { render :show, status: :ok, location: @banner }
      else
        format.html { render :edit }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1
  # DELETE /banners/1.json
  def destroy
    @banner.destroy
    respond_to do |format|
      format.html { redirect_to banners_url, notice: 'Баннер удален' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banner
      @banner = Banner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banner_params
      params.require(:banner).permit(:picture, :branch_id, :description, :uri)
    end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_form.html.erb
<%= render file: 'layouts/notify' %>

<div class="callout">
  <%= simple_form_for(@banner, html: {multipart: true}) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :branch, label: 'Филиал' %>

    <div class="preview-box"><img id = 'preview' alt = 'Нет изображения' src="<%= banner.picture_url if banner.picture?%>") %></div>
    <%= f.file_field :picture, label: 'Изображение' %>
    <%= f.input :description, label: 'Текст' %>
    <%= f.input :uri, label: 'Ссылка' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'OK' %>
  </div>
<% end %>
</div>

<script type="text/javascript">
function readURL(input) {
  if (input.files && input.files[0]) {
    var reader = new FileReader();
    reader.onload = function (e) {
      $('#preview').attr('src', e.target.result);
    }
    reader.readAsDataURL(input.files[0]);
  }
}
$("#banner_picture").change(function(){
  readURL(this);
});
</script>

app/views/banners/edit.html.erb
<%= render 'form', banner: @banner %>

app/views/banners/index.html.erb
<a href="<%= new_banner_path %>" class="button">Добавить баннер</a>
<div class="grid-x">
  <div class="cell small-12 medium-3">Изображение</div>
  <div class="cell small-12 medium-3">Текст</div>
  <div class="cell small-12 medium-3">Ссылка</div>
  <div class="cell small-12 medium-3"></div>
    <% @banners.each do |banner| %>
      <div class="cell small-12 medium-3"><div class="preview-box"><%= image_tag(banner.picture_url) if banner.picture? %></div></div>
      <div class="cell small-12 medium-3"><%= banner.description %></div>
      <div class="cell small-12 medium-3"><%= banner.uri %></div>
      <div class="cell small-12 medium-3">
        <%= link_to 'Изменить', edit_banner_path(banner) %>
        <%= link_to 'Удалить', banner, method: :delete, data: { confirm: 'Are you sure?' } %></div>
    <% end %>
</div>

app/views/banners/new.html.erb
<%= render 'form', banner: @banner %>

app/views/banners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Picture:</strong>
  <%= @banner.picture %>
</p>

<p>
  <strong>Description:</strong>
  <%= @banner.description %>
</p>

<p>
  <strong>Uri:</strong>
  <%= @banner.uri %>
</p>

<%= link_to 'Edit', edit_banner_path(@banner) %> |
<%= link_to 'Back', banners_path %>