config/routes.rb
Rails.application.routes.draw do
  resources :options
  resources :newslines
  resources :orders
  get 'bsd-banner', to: 'bannerpartner#index'
  get '/privacy', to: 'infopersonal#index'
  get '/loyalty', to: 'loyalty#index'
  resources :banners
  resources :userroles
  resources :storages
  resources :posts
  # resources :titles
  resources :branches
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :cities

  get 'persons/profile'
  get 'home/index'
  get '/about', to: 'about#index'
  get '/order', to: 'order#index'
  get '/branch_list', to: 'branches#list'

  root to: 'home#index'
end

app/models/banner.rb
class Banner < ApplicationRecord
  mount_uploader :picture, ImageUploader
  belongs_to :branch
end

app/models/branch.rb
class Branch < ApplicationRecord
  has_many :storage, dependent: :destroy
  mount_uploader :background, ImageUploader
  has_many :banners

  has_many :users, through: :branchadmins
  has_many :newslines
end

app/models/cargo.rb
class Cargo < ApplicationRecord
  has_many :orders, dependent: :destroy
end

app/models/city.rb
class City < ApplicationRecord

end

app/models/coin.rb
class Coin < ApplicationRecord
  belongs_to :user
end

app/models/location.rb
class Location < ActiveRecord::Base
  acts_as_mappable :default_units => :miles,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :theme
end

app/models/newsline.rb
class Newsline < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :branch
end

app/models/option.rb
class Option < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  scope :empty_results, -> { where(id: '-1') }
  
  belongs_to :user
  belongs_to :cargo
  belongs_to :payment
  belongs_to :status
end
# o = Order.where(code: 'CC-144-CT-493')

app/models/payment.rb
class Payment < ApplicationRecord
  has_many :order, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :title
  belongs_to :branch
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :userroles
  has_many :users, through: :userroles
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :orders
end

app/models/storage.rb
class Storage < ApplicationRecord
  belongs_to :branch
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_one :theme
end

app/models/title.rb
class Title < ApplicationRecord
  has_one :post
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :coins, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :userroles
  has_many :roles, through: :userroles

  has_many :branchadmins
  has_many :branches, through: :branchadmins

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    !roles.find_by_id(1).nil?
  end
  def director?
    !roles.find_by_id(2).nil?
  end
  def manager?
    !roles.find_by_id(3).nil?
  end
end

app/models/userrole.rb
class Userrole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include GeokitHelper
  def index
      @title = "Грузоперевозки по России от 1 кг"
      @banners = Banner.all
      b = near_branch
      @nearbranch = ""
      if !b.nil?
        @nearbranch = "<div style='position:relative;margin-top:80%;line-height: 1rem;'><b>#{b.name}<b><br>#{b.phone}<div>"
      end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="grid-x slideLeft">
  <div class="cell small-12 small-order-1 medium-order-1 medium-6 large-order-1 large-3">
    <div class="grid-y">
      <div class="cell small-8">
        <div class="grid-x">
          <div class="cell small-8">
            <div class='box'>
              <div class='content'>
                <a href="<%= about_path %>">
                  <div class="xcard xcrard-large color4">
                    <div class="metro-theme-ui">
                      <div class="metro-ui-row">
                        <div class="metro-ui-col-10">
                          <div class="metro-ui-column" data-switch="true" data-switches='[{"image": "<%= image_url("logo-white.svg") %>", "content": "<%= @nearbranch %>"}, { "image": "<%= image_url("red-bg.svg") %>", "content": "<h3>Республика Крым</h3><h5>Cнижаем стоимость 15%</h5>"}]'></div>
                        </div>
                      </div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <div class="cell small-4">
            <div class="grid-x">
              <div class="cell small-12">
                <div class='box'>
                  <div class='content'>
                    <a href="<%= branch_list_path %>">
                      <div class="xcard xcrard-medium color1">
                        <%= inline_svg "location.svg", class: 'medium-icon' %>
                      </div>
                    </a>
                  </div>
                </div>

              </div>
              <div class="cell small-12">
                <div class='box'>
                  <div class='content'>
                    <a href="<%= orders_path %>">
                      <div class="xcard xcrard-medium color17">
                        <%= inline_svg "search.svg", class: 'medium-icon' %>
                      </div>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="cell small-4">
        <div class="grid-x">
          <div class="cell small-4">
            <div class='box'>
              <div class='content'>
                <a href="<%= user_signed_in? ? persons_profile_path : new_user_session_path %>">
                  <div class="xcard xcrard-medium color16">
                    <%= inline_svg "user.svg", class: 'medium-icon' %>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <div class="cell small-8">
            <div class='rect'>
              <div class='content'>
                <a class="htooltip" href="<%= new_order_path %>">
                  <div class="xcard color14 xcrard-medium">
                    <%= inline_svg "truck.svg", class: 'rect-icon' %>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="cell small-4 show-for-large">
        <div class="grid-x">
          <div class="cell small-4">
            <div class="grid-x">
              <div class="cell small-6">
                <div class='box'>
                  <div class='content'>
                    <a class="htooltip" href="<%= loyalty_path %>">
                      <span>
                        <b>Программа лояльности клиентов</b><br>
                        <% if user_signed_in? %>
                          На вашем бонусном счету:
                          <%= amount_coin(current_user.id) %>
                          руб.
                        <% else %>
                          Зарегистрируйтесь на нашем сайте и получите 100 рублей на свой бонусный счет
                        <% end %>
                      </span>
                      <div class="xcard xcrard-small color29">
                        <%= inline_svg "gift.svg", class: 'small-icon' %>
                      </div>
                    </a>
                  </div>
                </div>
              </div>
              <div class="cell small-6">
                <div class='box'>
                  <div class='content'>
                    <div class="xcard xcrard-small color21">
                      <%= inline_svg "info.svg", class: 'small-icon' %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="cell small-6">
                <div class='box'>
                  <div class='content'>
                    <a class="htooltip" href="<%= new_post_path %>">
                      <span>
                        <b>Служба контроля качества</b><br>Напишите, что Вы думаете о нашей работе,<br>Ваш отзыв очень важен для нас</span>
                      <div class="xcard xcrard-small color12">
                        <%= inline_svg "complaint.svg", class: 'small-icon' %>
                      </div>
                    </a>
                  </div>
                </div>
              </div>
              <div class="cell small-6">
                <div class='box'>
                  <div class='content'>
                    <div class="xcard xcrard-small color-case">
                      <%= inline_svg "case.svg", class: 'small-icon' %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="cell small-8">
            <div class='rect'>
              <div class='content'>
                <div class="xcard xcrard-medium color-case">
                  <%= render file: 'template/minibanner' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="cell small-12 small-order-3 medium-order-3 medium-12 large-order-2 large-6">
    <%= render file: 'template/mainbanner' %>
  </div>

  <div class="cell small-12 small-order-2 medium-order-2 medium-6 large-order-3 large-3">
    <%= render file: 'template/calc' %>
  </div>
</div>