config/routes.rb
Rails.application.routes.draw do
  resources :options
  resources :newslines
  resources :orders
  get 'bsd-banner', to: 'bannerpartner#index'
  get '/privacy', to: 'infopersonal#index'
  get '/loyalty', to: 'loyalty#index'
  resources :banners
  resources :userroles
  resources :storages
  resources :posts
  # resources :titles
  resources :branches
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :cities

  get 'persons/profile'
  get 'home/index'
  get '/about', to: 'about#index'
  get '/order', to: 'order#index'
  get '/branch_list', to: 'branches#list'

  root to: 'home#index'
end

app/models/banner.rb
class Banner < ApplicationRecord
  mount_uploader :picture, ImageUploader
  belongs_to :branch
end

app/models/branch.rb
class Branch < ApplicationRecord
  has_many :storage, dependent: :destroy
  mount_uploader :background, ImageUploader
  has_many :banners

  has_many :users, through: :branchadmins
  has_many :newslines
end

app/models/branchadmin.rb
class Branchadmin < ApplicationRecord
  belongs_to :branch
  belongs_to :user
end

app/models/cargo.rb
class Cargo < ApplicationRecord
  has_many :orders, dependent: :destroy
end

app/models/city.rb
class City < ApplicationRecord

end

app/models/coin.rb
class Coin < ApplicationRecord
  belongs_to :user
end

app/models/location.rb
class Location < ActiveRecord::Base
  acts_as_mappable :default_units => :miles,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :theme
end

app/models/newsline.rb
class Newsline < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :branch
end

app/models/option.rb
class Option < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  scope :empty_results, -> { where(id: '-1') }
  
  belongs_to :user
  belongs_to :cargo
  belongs_to :payment
  belongs_to :status
end
# o = Order.where(code: 'CC-144-CT-493')

app/models/payment.rb
class Payment < ApplicationRecord
  has_many :order, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :title
  belongs_to :branch
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :userroles
  has_many :users, through: :userroles
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :orders
end

app/models/storage.rb
class Storage < ApplicationRecord
  belongs_to :branch
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_one :theme
end

app/models/title.rb
class Title < ApplicationRecord
  has_one :post
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :coins, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :userroles
  has_many :roles, through: :userroles

  has_many :branchadmins
  has_many :branches, through: :branchadmins

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    !roles.find_by_id(1).nil?
  end
  def director?
    !roles.find_by_id(2).nil?
  end
  def manager?
    !roles.find_by_id(3).nil?
  end
end

app/models/userrole.rb
class Userrole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/storages_controller.rb
class StoragesController < ApplicationController
  before_action :set_storage, only: [:show, :edit, :update, :destroy]

  # GET /storages
  # GET /storages.json
  def index
    @storages = Storage.all
  end

  # GET /storages/1
  # GET /storages/1.json
  def show
    b = Branch.find(@storage.branch_id)
    @title = "Филиал #{b.name}"
  end

  # GET /storages/new
  def new
    @storage = Storage.new
    @title = 'Добавить терминал'
  end

  # GET /storages/1/edit
  def edit
    @title = 'Изменить адрес терминала'
  end

  # POST /storages
  # POST /storages.json
  def create
    @storage = Storage.new(storage_params)
    @title = 'Добавить терминал'

    respond_to do |format|
      if @storage.save
        format.html { redirect_to @storage, notice: 'Адрес склада успешно добавлен' }
        format.json { render :show, status: :created, location: @storage }
      else
        format.html { render :new }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /storages/1
  # PATCH/PUT /storages/1.json
  def update
    respond_to do |format|
      if @storage.update(storage_params)
        format.html { redirect_to @storage, notice: 'Информация о складе изменена' }
        format.json { render :show, status: :ok, location: @storage }
      else
        format.html { render :edit }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /storages/1
  # DELETE /storages/1.json
  def destroy
    @storage.destroy
    respond_to do |format|
      format.html { redirect_to storages_url, notice: 'Сведения о складе удалены' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_storage
      @storage = Storage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def storage_params
      params.require(:storage).permit(:branch_id, :address, :latitude, :longitude)
    end
end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/views/storages/_form.html.erb
<%= simple_form_for(@storage) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs callout">
    <div class="grid-x grid-margin-x">
      <div class="cell small-12">
        <%= f.association :branch, :collection => current_user.branches, include_blank: false, label: 'Филиал' %>
      </div>
      <div class="cell small-12 floated-label-wrapper">
        <%= f.input :address, label: 'Адрес склада', as: :string, :placeholder => "Адрес склада" %>
      </div>
      <div class="cell small-6 floated-label-wrapper">
        <%= f.input :latitude, as: :string, label: 'Широта:', :placeholder => 'Широта' %>
      </div>
      <div class="cell small-6 floated-label-wrapper">
        <%= f.input :longitude, as: :string, label: 'Долгота', :placeholder => 'Долгота' %>
      </div>
    </div>

    <link href="https://cdn.jsdelivr.net/npm/suggestions-jquery@18.8.0/dist/css/suggestions.min.css" type="text/css" rel="stylesheet" />
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <!--[if lt IE 10]>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajaxtransport-xdomainrequest/1.0.1/jquery.xdomainrequest.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/suggestions-jquery@18.8.0/dist/js/jquery.suggestions.min.js"></script>
    <script type="text/javascript">
    var showClass = 'show';

    $('input').on('checkval', function () {
      var label = $(this).prev('label');
      if (this.value !== '') {
        label.addClass(showClass);
      } else {
        label.removeClass(showClass);
      }
    }).on('keyup', function () {
      $(this).trigger('checkval');
    });
        $("#storage_address").suggestions({
            token: "f2bbb5624fd5b6295a9207033ca2449935340869",
            type: "ADDRESS",
            count: 5,
            onSelect: function(suggestion) {
                $("#storage_latitude").val(suggestion["data"]["geo_lat"]);
                $("#storage_longitude").val(suggestion["data"]["geo_lon"]);
            }
        });
    </script>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'OK' %>
  </div>
<% end %>

app/views/storages/edit.html.erb
<%= render 'form', storage: @storage %>

app/views/storages/index.html.erb
<div data-closable class="notice callout alert-callout-subtle primary small success">
  <%= notice %>
  <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
    <span aria-hidden="true">⊗</span>
  </button>
</div>
<a href="<%= new_storage_path %>" class="button">Добавить терминал</a>
<div class="grid-x">
  <% @storages.each do |storage| %>
    <div class="cell small-12 medium-6"><%= storage.address %></div>
    <div class="cell small-4 medium-2"><%= link_to 'Показать', storage %></div>
    <div class="cell small-4 medium-2"><%= link_to 'Изменить', edit_storage_path(storage) %></div>
    <div class="cell small-4 medium-2"><%= link_to 'Удалить', storage, method: :delete, data: { confirm: 'Вы уверены?' } %></div>
  <% end %>
</div>

app/views/storages/list.html.erb
<ul>
  <% @storages.each do |storage| %>
    <li>
      <% branch = Branches.find(storage.branch_id) %>
      <h1><%= branch.name %></h1>
      <p></p>
      <%= link_to 'Подробнее', storage %>
    </li>
  <% end %>
</ul>

<table>
  <thead>
    <tr>
      <th>Branch</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @storages.each do |storage| %>
      <tr>
        <td><%= storage.branch_id %></td>
        <td><%= storage.address %></td>
        <td><%= storage.latitude %></td>
        <td><%= storage.longitude %></td>
        <td><%= link_to 'Show', storage %></td>
        <td><%= link_to 'Edit', edit_storage_path(storage) %></td>
        <td><%= link_to 'Destroy', storage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/storages/new.html.erb
<%= render 'form', storage: @storage %>

<%= link_to 'Back', storages_path %>

app/views/storages/show.html.erb
<script src="https://api-maps.yandex.ru/2.0-stable/?load=package.standard&lang=ru-RU" type="text/javascript"></script>
<script type="text/javascript">
    ymaps.ready(init);
    var myMap,
        myPlacemark;

    function init(){
        myMap = new ymaps.Map ("map", {
            center: [<%= @storage.latitude %>, <%= @storage.longitude %>],
            zoom: 14,
            controls: ['typeSelector', 'trafficControl', 'fullscreenControl']
        });

        myPlacemark = new ymaps.Placemark([<%= @storage.latitude %>, <%= @storage.longitude %>], {
            hintContent: 'Балтийская служба доставки'
        }, {
        iconImageHref: "<%= image_url('mapicon.png') %>",
        iconImageSize: [30, 42],
        iconImageOffset: [-3, -42]});

        myMap.geoObjects.add(myPlacemark);
    }
</script>

<% branch = Branch.find(@storage.branch_id) %>

<%= render file: 'layouts/notify' %>

<div class="grid-x callout grid-margin-x" style="min-height: 350px">
  <div class="cell small-12 medium-6">
    <%= image_tag(branch.background.url) if branch.background? %>
    <p>
      <strong>Адрес: </strong><%= @storage.address %><br>
      <strong>Телефон: </strong><%= tel_to branch.phone %><br>
      <strong>E-mail: </strong><%= mail_to branch.email %><br>
      <%= link_to "Реквизиты филиала (PDF)", branch_path(branch, :pdf) %>
    </p>
    <strong>О филиале:</strong>
    <p>
      <%= branch.description %>
    </p>
  </div>
  <div class="cell small-12 medium-6">
    <div id="map" style="width: 100%; height: 100%;"></div>
  </div>
</div>
<!-- <%= link_to 'Edit', edit_storage_path(@storage) %> |
<%= link_to 'Back', storages_path %> -->